steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/mediabrowser/mediabrowser', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/mediabrowser/mediabrowser']
  - name: gcr.io/cloud-builders/gcloud
    args: ['run', 'deploy', 'mediabrowser', '--platform', 'managed', '--region', '$_REGION',
           '--image', '$_REGION-docker.pkg.dev/$PROJECT_ID/mediabrowser/mediabrowser:latest', '--allow-unauthenticated',
           '--service-account', '$_SERVICE_ACCOUNT_EMAIL',
           '--set-env-vars', 'BUCKET_NAME=$_BUCKET_NAME,WEB_USERNAME=$_WEB_USERNAME,WEB_PASSWORD=$_WEB_PASSWORD,PK_SECRET_NAME=$_PK_SECRET_NAME,SERVICE_ACCOUNT_NAME=$_SERVICE_ACCOUNT_EMAIL']
substitutions:
  _REGION: us-east1
  _BUCKET_NAME: mediabrowser
